#!/bin/bash
#
# Author: Simon Rydell
# Date: 1 May 2018
#
# Restore backup of directory ~/Dokument/Forskning using git.
# Backups are stored in a private git repository

# Change to the right directory
cd $HOME/Dokument/Forskning

# Get the latest commit hash
latestSHA=$(git log | head -n1 | sed 's/^commit //')

# Get the current time
# Format: YYYY-MM-DD_HH-mm-ss
TIMEOFBACKUP=$(date +%x_%H-%M-%S)

# This will be the branch name AND the commit message on that branch
SAVEMESSAGE="Saved_state_from_$TIMEOFBACKUP"

# Create a branch where we will save what we want to revert from
# It is garanteed to be unique due to $TIMEOFBACKUP
git checkout -b "$SAVEMESSAGE"

# Save what we will revert from
git add .
git commit -m "$SAVEMESSAGE"

# Push our saved state
git push --set-upstream origin "$SAVEMESSAGE"

# Go back to master branch
git checkout master

# Revert back to the latest commit before save. 
# NOTE: On its own this is dangerous,
#	here it's safe since we trust the previous save
git reset --hard $latestSHA

# Free up the variable names
unset TIMEOFBACKUP
unset latestSHA
unset SAVEMESSAGE
